### ISSUE TITLE
Add support for flood fill navmesh pruning

### ISSUE THREAD

**Issue by isaac-mason** [isaac-mason/recast-navigation-js#156]
See flood pruning functionality in RecastDemo: https://github.com/recastnavigation/recastnavigation/blob/cd898904b72a300011fbb24d578620bafa08ef2c/RecastDemo/Source/NavMeshPruneTool.cpp#L132

Related google discussion: https://groups.google.com/g/recastnavigation/c/v2XwKzq-NZs/m/ZCEwcVHHmCMJ

**Comment by yelouafi** [comment]
not sure if it's related but I'll report here

[mode](https://res.cloudinary.com/oncybertesting/raw/upload/v1695808980/1695808979-uploaded-assets/c56f7fb49c80c06f1becf5220189b22428fa26fe0d68e9e105f749367ca9c8d5.glb)

generate with cell size: 0.5, tileSize: 32, walkableHieght and walkableClimb 4

agent sometimes fail to crosse between tiles

![Screenshot 2023-09-27 at 11 12 13](https://github.com/isaac-mason/recast-navigation-js/assets/5453835/d9d6e684-f268-4bd7-9c46-dbdf348454bb)

sometimes it disappears, turns out it falls under the platform

![Screenshot 2023-09-27 at 11 17 32](https://github.com/isaac-mason/recast-navigation-js/assets/5453835/a88f8ccb-5730-4dca-bbe8-79c39391ce00)
