### ISSUE TITLE
agent teleport wrong position in storybook

### ISSUE THREAD

**Issue by o0olele** [isaac-mason/recast-navigation-js#381]
- in this example, https://recast-navigation-js.isaacmason.com/?path=/story/crowd-crowd-with-single-agent--crowd-with-single-agent ，when clicked this area, agent teleport a point under the ramp
![image](https://github.com/isaac-mason/recast-navigation-js/assets/43069191/af382292-93b8-456f-a45b-899371800ac2)

**Comment by GGAlanSmithee** [comment]
I've actually also noticed this in y own maps, with overlapping geometry (which I since removed, since I could not get the configuration correct, to not display this behavior).

There seems to be a cut off right next to the top of the ramp, where (I guess) it's high enough above the underlying mesh.

https://github.com/isaac-mason/recast-navigation-js/assets/11805103/62010482-a539-4ce5-811b-4add00f46b36

**Comment by isaac-mason** [comment]
I'm aware of this but haven't done much investigation as off yet.

This recastnavigation google discussion seems related: https://groups.google.com/g/recastnavigation/c/idkwKdgChlA/m/00Sr7FKzfEoJ

**Comment by isaac-mason** [comment]
fixed by https://github.com/isaac-mason/recast-navigation-js/pull/454

**Comment by GGAlanSmithee** [comment]
I was hoping this would be fixed by that, amazing! Thanks @yelouafi you're a legend!
